name: Keep Alive Render

on:
  schedule:
    # Corre a cada 13 minutos
    - cron: "*/13 * * * *"
  workflow_dispatch: # Permite correr o script manualmente no GitHub se for preciso

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Keep Alive Script
        run: node keep-alive.js
